add build agent pr:

diff --git a/.github/workflows/push-release.yml b/.github/workflows/push-release.yml
--- a/.github/workflows/push-release.yml
+++ b/.github/workflows/push-release.yml
@@ -140,7 +140,8 @@ jobs:
     strategy:
       matrix:
         os: [linux]
-        arch: [amd64, arm64]
+        arch: [amd64]
+        # arch: [amd64, arm64]
     services:
       registry:
         image: registry:2
@@ -200,6 +201,87 @@ jobs:
             "RANCHER_TAG=${{ env.TAG }}"
             "RANCHER_REPO=${{ env.REPOSITORY_OWNER }}"
             "REGISTRY=${{ env.REGISTRY }}"
+          tags: ${{ env.IMAGE_AGENT }}:${{ env.TAG }}-${{ matrix.arch }}
+          context: .
+          platforms: "${{ matrix.os }}/${{ matrix.arch }}"
+          file: ./package/Dockerfile.agent
+          labels: "${{ steps.meta.outputs.labels }}"
+          outputs: type=docker,dest=/tmp/rancher-agent-${{ matrix.os }}-${{ matrix.arch }}.tar
+      - name: Upload image
+        uses: actions/upload-artifact@v4
+        with:
+          name: "rancher-agent-${{ matrix.os }}-${{ matrix.arch }}"
+          path: /tmp/rancher-agent-${{ matrix.os }}-${{ matrix.arch }}.tar
+          if-no-files-found: error
+          retention-days: 1
+          overwrite: false
+  build-agent-pr:
+    # needs: [build-server]
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        os: [linux]
+        arch: [amd64]
+        # arch: [amd64, arm64]
+    services:
+      registry:
+        image: registry:2
+        ports:
+          - 5000:5000
+    env:
+      REGISTRY: "127.0.0.1:5000"
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Clean runner
+        run: |
+          sudo rm -rf /usr/share/dotnet
+          sudo rm -rf /opt/ghc
+          sudo rm -rf "/usr/local/share/boost"
+          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+      - name: Setup Environment Variables
+        run: |
+          echo "ARCH=${{ matrix.arch }}" >> "$GITHUB_ENV"
+      - name: Docker meta
+        id: meta
+        uses: docker/metadata-action@v5
+        with:
+          images: ${{ env.IMAGE }}
+          flavor: |
+            latest=false
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+        with:
+          driver-opts: network=host
+      - name: Download rancher image
+        uses: actions/download-artifact@v4
+        with:
+          name: "rancher-${{ matrix.os }}-${{ matrix.arch }}"
+          path: /tmp
+          run-id: 9960044387
+          github-token: ${{ github.token }}
+      - name: Load image
+        run: |
+          image_id=$(docker load --input /tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar 2>&1 | grep "Loaded image" | awk '{print $NF}')
+          if [ -z "$image_id" ]; then
+            echo "Error: Failed to load image from tarball!"
+            exit 1
+          fi
+          docker tag "$image_id" ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
+          docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
+      - name: Build agent
+        id: build
+        uses: docker/build-push-action@v5
+        with:
+          push: false
+          build-args: |
+            "VERSION=${{ env.TAG }}"
+            "ARCH=${{ matrix.arch }}"
+            "RANCHER_TAG=${{ env.TAG }}"
+            "RANCHER_REPO=${{ env.REPOSITORY_OWNER }}"
+            "REGISTRY=localhost:5000"
           tags: ${{ env.IMAGE_AGENT }}:${{ env.TAG }}-${{ matrix.arch }}
           context: .
           platforms: "${{ matrix.os }}/${{ matrix.arch }}"
